name: Build Wheels

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_wheels:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    name: Build wheels on ${{ matrix.os }}

    permissions:
      contents: write # svenstaro/upload-release-action 

    steps:
      - uses: actions/checkout@v4

      - name: Checkout sentencepiece repo
        uses: actions/checkout@v4
        with:
          repository: google/sentencepiece
          path: sentencepiece
          ref: v0.2.0

      - name: Apply patches to sentencepiece
        working-directory: ${{github.workspace}}/sentencepiece
        run: |
          git apply ${{github.workspace}}/patches/add-missing-cstdint.patch
          git apply ${{github.workspace}}/patches/bump-cmake-minimum-required-version.patch
          git apply ${{github.workspace}}/patches/fix-crash-in-unigram-model-training.patch
          git apply ${{github.workspace}}/patches/general-ci-refresh.patch
          
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build for Windows
        if: runner.os == 'Windows'
        working-directory: ${{github.workspace}}/sentencepiece
        run: |
          cmake -A Win32 -B build_win32 -DSPM_ENABLE_SHARED=OFF -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/sentencepiece/build/root_win32
          cmake --build build_win32 --config Release --target install --parallel 8
          cmake -A x64   -B build_amd64 -DSPM_ENABLE_SHARED=OFF -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/sentencepiece/build/root_amd64
          cmake --build build_amd64 --config Release --target install --parallel 8
          cmake -A arm64 -B build_arm64 -DSPM_ENABLE_SHARED=OFF -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/sentencepiece/build/root_arm64
          cmake --build build_arm64 --config Release --target install --parallel 8

      - name: Build for Mac
        if: runner.os == 'macOS'
        working-directory: ${{github.workspace}}/sentencepiece
        run: |
          cmake -B build -DSPM_ENABLE_SHARED=OFF -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/sentencepiece/build/root
          cmake --build build --config Release --target install --parallel 8
        env:
          CMAKE_OSX_ARCHITECTURES: arm64;x86_64

      - name: Install cibuildwheel
        working-directory: ${{github.workspace}}/sentencepiece/python
        run: |
          pip install --require-hashes --no-dependencies -r ../.github/workflows/requirements/base.txt
          pip install --require-hashes --no-dependencies -r ../.github/workflows/requirements/cibuildwheel.txt

      - name: Print cibuildwheel
        working-directory: ${{github.workspace}}/sentencepiece/python
        run: python -m cibuildwheel --print-build-identifiers
        env:
          CIBW_BUILD: cp313-*
          CIBW_SKIP: pp* *-musllinux_*

      - name: Replace symlinks
        working-directory: ${{github.workspace}}/sentencepiece
        run: |
          # Replace external symlinks with copies to avoid issues with cibuildwheel
          rm python/test/botchan.txt
          cp data/botchan.txt python/test/

      - name: Build wheels
        working-directory: ${{github.workspace}}/sentencepiece
        run: |
          python -m cibuildwheel --output-dir python/wheelhouse python
        env:
          CIBW_ARCHS_LINUX: auto
          CIBW_ARCHS_MACOS: x86_64 universal2 arm64
          CIBW_ARCHS_WINDOWS: auto ARM64
          CIBW_BUILD: cp313-*
          CIBW_SKIP: pp* *-musllinux_*
          CIBW_BUILD_VERBOSITY: 1
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {project}/python/test

      - name: Build sdist archive
        working-directory: ${{github.workspace}}/sentencepiece/python
        run: sh build_sdist.sh

      - name: Validate sdist archive
        working-directory: ${{github.workspace}}/sentencepiece
        run: twine check python/dist/*.tar.gz

      - name: Build wheel from sdist
        working-directory: ${{github.workspace}}/sentencepiece
        shell: bash
        run: python -m pip wheel python/dist/*.tar.gz --verbose

      - name: Copy sdist
        working-directory: ${{github.workspace}}/sentencepiece/python
        if: runner.os == 'macOS'
        run: cp -f dist/*.tar.gz wheelhouse/

      - name: Upload wheel release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./sentencepiece/python/wheelhouse/*
          tag: v0.2.0
          overwrite: true
          file_glob: true
